In [127]:
pwd

u'C:\\Users\\fcont\\Documents\\Python Master\\Corey'

In [114]:
#based on https://www.youtube.com/watch?v=Q06Y3DUSwz4

In [115]:
import pandas as pd
statesLFP = pd.read_excel('C:\\Users\\fcont\\Documents\\Python Master\\Corey\\State-LFPRates.xlsx',0)
statesLFP.head(5)

,FIPS Code,State and area,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate
0,1,Alabama,1976,1,2605000,1492409,57.3,1392154,53.4,100255,6.7
1,2,Alaska,1976,1,232000,159154,68.6,147809,63.7,11345,7.1
2,4,Arizona,1976,1,1621000,972413,60.0,872738,53.8,99675,10.3
3,5,Arkansas,1976,1,1536000,882835,57.5,817756,53.2,65079,7.4
4,6,California,1976,1,15621000,9781720,62.6,8892663,56.9,889057,9.1

In [116]:
#statesLFP[statesLFP['State and area']=='Massachusetts'].describe()
statesLFP[statesLFP['State and area']=='Massachusetts']

,FIPS Code,State and area,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate
22,25,Massachusetts,1976,1,4194000,2715161,64.7,2435124,58.1,280037,10.3
75,25,Massachusetts,1976,2,4198000,2714974,64.7,2434220,58.0,280754,10.3
128,25,Massachusetts,1976,3,4201000,2715650,64.6,2435324,58.0,280326,10.3
181,25,Massachusetts,1976,4,4204000,2717527,64.6,2441683,58.1,275844,10.2
234,25,Massachusetts,1976,5,4207000,2719627,64.6,2450016,58.2,269611,9.9
287,25,Massachusetts,1976,6,4210000,2721925,64.7,2459155,58.4,262770,9.7
340,25,Massachusetts,1976,7,4213000,2723542,64.6,2467055,58.6,256487,9.4
393,25,Massachusetts,1976,8,4217000,2724895,64.6,2473326,58.7,251569,9.2
446,25,Massachusetts,1976,9,4220000,2726270,64.6,2478825,58.7,247445,9.1
499,25,Massachusetts,1976,10,4224000,2727715,64.6,2483762,58.8,243953,8.9
552,25,Massachusetts,1976,11,4227000,2729521,64.6,2488634,58.9,240887,8.8
605,25,Massachusetts,1976,12,4231000,2732178,64.6,2494193,59.0,237985,8.7
658,25,Massachusetts,1977,1,4234000,2736372,64.6,2501143,59.1,235229,8.6
711,25,Massachusetts,1977,2,4238000,2741918,64.7,2509691,59.2,232227,8.5
764,25,Massachusetts,1977,3,4242000,2748044,64.8,2519277,59.4,228767,8.3
817,25,Massachusetts,1977,4,4245000,2754308,64.9,2529103,59.6,225205,8.2
870,25,Massachusetts,1977,5,4249000,2759927,65.0,2538267,59.7,221660,8.0
923,25,Massachusetts,1977,6,4252000,2764312,65.0,2546166,59.9,218146,7.9
976,25,Massachusetts,1977,7,4256000,2767582,65.0,2553077,60.0,214505,7.8
1029,25,Massachusetts,1977,8,4260000,2770477,65.0,2560004,60.1,210473,7.6
1082,25,Massachusetts,1977,9,4263000,2773738,65.1,2567798,60.2,205940,7.4
1135,25,Massachusetts,1977,10,4267000,2777470,65.1,2576525,60.4,200945,7.2
1188,25,Massachusetts,1977,11,4270000,2781371,65.1,2585669,60.6,195702,7.0
1241,25,Massachusetts,1977,12,4274000,2785021,65.2,2594434,60.7,190587,6.8
1294,25,Massachusetts,1978,1,4277000,2788534,65.2,2602710,60.9,185824,6.7
1347,25,Massachusetts,1978,2,4281000,2792371,65.2,2610452,61.0,181919,6.5
1400,25,Massachusetts,1978,3,4285000,2796729,65.3,2617592,61.1,179137,6.4
1453,25,Massachusetts,1978,4,4288000,2801362,65.3,2624190,61.2,177172,6.3
1506,25,Massachusetts,1978,5,4292000,2806240,65.4,2630614,61.3,175626,6.3
1559,25,Massachusetts,1978,6,4295000,2811159,65.5,2637168,61.4,173991,6.2
...,...,...,...,...,...,...,...,...,...,...,...
25250,25,Massachusetts,2015,9,5512536,3578676,64.9,3412307,61.9,166369,4.6
25303,25,Massachusetts,2015,10,5516309,3578931,64.9,3415105,61.9,163826,4.6
25356,25,Massachusetts,2015,11,5519439,3581595,64.9,3420236,62.0,161359,4.5
25409,25,Massachusetts,2015,12,5522696,3585704,64.9,3426975,62.1,158729,4.4
25462,25,Massachusetts,2016,1,5525159,3589877,65.0,3434271,62.2,155606,4.3
25515,25,Massachusetts,2016,2,5527772,3593476,65.0,3441464,62.3,152012,4.2
25568,25,Massachusetts,2016,3,5530637,3596491,65.0,3448421,62.4,148070,4.1
25621,25,Massachusetts,2016,4,5533713,3599500,65.0,3455387,62.4,144113,4.0
25674,25,Massachusetts,2016,5,5536949,3603159,65.1,3462678,62.5,140481,3.9
25727,25,Massachusetts,2016,6,5540261,3607475,65.1,3470112,62.6,137363,3.8
25780,25,Massachusetts,2016,7,5543933,3612256,65.2,3477347,62.7,134909,3.7
25833,25,Massachusetts,2016,8,5547759,3617304,65.2,3483842,62.8,133462,3.7
25886,25,Massachusetts,2016,9,5551661,3622622,65.3,3489203,62.8,133419,3.7
25939,25,Massachusetts,2016,10,5555743,3628128,65.3,3493493,62.9,134635,3.7
25992,25,Massachusetts,2016,11,5559317,3633941,65.4,3497398,62.9,136543,3.8
26045,25,Massachusetts,2016,12,5562675,3640083,65.4,3501473,62.9,138610,3.8
26098,25,Massachusetts,2017,1,5566189,3646271,65.5,3505786,63.0,140485,3.9
26151,25,Massachusetts,2017,2,5568803,3651878,65.6,3510163,63.0,141715,3.9
26204,25,Massachusetts,2017,3,5571734,3656082,65.6,3513943,63.1,142139,3.9
26257,25,Massachusetts,2017,4,5574788,3658885,65.6,3517167,63.1,141718,3.9
26310,25,Massachusetts,2017,5,5578204,3660570,65.6,3520112,63.1,140458,3.8
26363,25,Massachusetts,2017,6,5581720,3661300,65.6,3522725,63.1,138575,3.8
26416,25,Massachusetts,2017,7,5585614,3661353,65.5,3525238,63.1,136115,3.7
26469,25,Massachusetts,2017,8,5589404,3660376,65.5,3526995,63.1,133381,3.6
26522,25,Massachusetts,2017,9,5593228,3659358,65.4,3528571,63.1,130787,3.6
26575,25,Massachusetts,2017,10,5597079,3658063,65.4,3529226,63.1,128837,3.5
26628,25,Massachusetts,2017,11,5600438,3657358,65.3,3528769,63.0,128589,3.5
26681,25,Massachusetts,2017,12,5603545,3657291,65.3,3528413,63.0,128878,3.5
26734,25,Massachusetts,2018,1,5606659,3659563,65.3,3532436,63.0,127127,3.5
26787,25,Massachusetts,2018,2,5609183,3669596,65.4,3541972,63.1,127624,3.5

In [ ]:
#football = pd.read_excel('football.xlsx', 'Sheet1')
#football

In [13]:
import pandas as pd
df= pd.read_excel('C:\\Users\\fcont\\Documents\\Python Master\\Corey\\State-LFPRates.xlsx',0)
df.head(5)
#for testing only use cell 2 code
#df.to_html('newfc.html')
#df  = pd.DataFrame('State-LFPRates.xlsx', columns=['State and area'])
'''df ['U-Rate'].mean()
df ['State and area'].count()
df ['CL-Pct of Pop.'].count()
#df[['State and area', 'U-Rate']][df.'U-Rate'==df['U-Rate'].max()]
df[['State and area', 'U-Rate']]
#df[df.['U-Rate']==10.6]
df[df['State and area']==[df['Massachusetts']]
df[df.State=="Massachusetts"]'''
df.columns
df

,FIPS Code,State and area,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate
0,1,Alabama,1976,1,2605000,1492409,57.3,1392154,53.4,100255,6.7
1,2,Alaska,1976,1,232000,159154,68.6,147809,63.7,11345,7.1
2,4,Arizona,1976,1,1621000,972413,60.0,872738,53.8,99675,10.3
3,5,Arkansas,1976,1,1536000,882835,57.5,817756,53.2,65079,7.4
4,6,California,1976,1,15621000,9781720,62.6,8892663,56.9,889057,9.1
5,37,Los Angeles County,1976,1,5273000,3375681,64.0,3078200,58.4,297481,8.8
6,8,Colorado,1976,1,1832000,1232334,67.3,1164563,63.6,67771,5.5
7,9,Connecticut,1976,1,2248000,1443606,64.2,1302422,57.9,141184,9.8
8,10,Delaware,1976,1,417000,262688,63.0,242382,58.1,20306,7.7
9,11,District of Columbia,1976,1,520000,339378,65.3,308820,59.4,30558,9.0
10,12,Florida,1976,1,6421000,3592149,55.9,3248523,50.6,343626,9.6
11,13,Georgia,1976,1,3522000,2250451,63.9,2061744,58.5,188707,8.4
12,15,Hawaii,1976,1,583000,408869,70.1,367414,63.0,41455,10.1
13,16,Idaho,1976,1,580000,366173,63.1,346216,59.7,19957,5.5
14,17,Illinois,1976,1,8127000,5133491,63.2,4788469,58.9,345022,6.7
15,18,Indiana,1976,1,3789000,2418961,63.8,2260951,59.7,158010,6.5
16,19,Iowa,1976,1,2066000,1324627,64.1,1269103,61.4,55524,4.2
17,20,Kansas,1976,1,1635000,1061055,64.9,1015585,62.1,45470,4.3
18,21,Kentucky,1976,1,2459000,1489641,60.6,1406646,57.2,82995,5.6
19,22,Louisiana,1976,1,2672000,1513827,56.7,1417816,53.1,96011,6.3
20,23,Maine,1976,1,764000,475639,62.3,433990,56.8,41649,8.8
21,24,Maryland,1976,1,2954000,1905561,64.5,1781850,60.3,123711,6.5
22,25,Massachusetts,1976,1,4194000,2715161,64.7,2435124,58.1,280037,10.3
23,26,Michigan,1976,1,6417000,3959251,61.7,3568988,55.6,390263,9.9
24,27,Minnesota,1976,1,2788000,1832797,65.7,1722777,61.8,110020,6.0
25,28,Mississippi,1976,1,1640000,961115,58.6,896774,54.7,64341,6.7
26,29,Missouri,1976,1,3464000,2088814,60.3,1963951,56.7,124863,6.0
27,30,Montana,1976,1,531000,327276,61.6,308066,58.0,19210,5.9
28,31,Nebraska,1976,1,1095000,715752,65.4,692137,63.2,23615,3.3
29,32,Nevada,1976,1,451000,322417,71.5,293574,65.1,28843,8.9
...,...,...,...,...,...,...,...,...,...,...,...
26788,26,Michigan,2018,2,7967153,4897505,61.5,4664835,58.6,232670,4.8
26789,27,Minnesota,2018,2,4393144,3085973,70.2,2986231,68.0,99742,3.2
26790,28,Mississippi,2018,2,2291935,1274048,55.6,1216375,53.1,57673,4.5
26791,29,Missouri,2018,2,4796357,3040940,63.4,2929814,61.1,111126,3.7
26792,30,Montana,2018,2,838288,526548,62.8,504872,60.2,21676,4.1
26793,31,Nebraska,2018,2,1472932,1009356,68.5,980975,66.6,28381,2.8
26794,32,Nevada,2018,2,2381974,1480436,62.2,1407920,59.1,72516,4.9
26795,33,New Hampshire,2018,2,1105804,747182,67.6,727999,65.8,19183,2.6
26796,34,New Jersey,2018,2,7180959,4506605,62.8,4297507,59.8,209098,4.6
26797,35,New Mexico,2018,2,1624419,935149,57.6,881222,54.2,53927,5.8
26798,36,New York,2018,2,15960578,9692497,60.7,9242364,57.9,450133,4.6
26799,51000,New York city,2018,2,6944935,4228210,60.9,4048517,58.3,179693,4.2
26800,37,North Carolina,2018,2,8101027,4974418,61.4,4751873,58.7,222545,4.5
26801,38,North Dakota,2018,2,579228,413631,71.4,402694,69.5,10937,2.6
26802,39,Ohio,2018,2,9213291,5765751,62.6,5504161,59.7,261590,4.5
26803,40,Oklahoma,2018,2,3004345,1845167,61.4,1770033,58.9,75134,4.1
26804,41,Oregon,2018,2,3361594,2129855,63.4,2041949,60.7,87906,4.1
26805,42,Pennsylvania,2018,2,10276743,6410846,62.4,6100869,59.4,309977,4.8
26806,44,Rhode Island,2018,2,864323,557339,64.5,532007,61.6,25332,4.5
26807,45,South Carolina,2018,2,3986188,2324714,58.3,2223298,55.8,101416,4.4
26808,46,South Dakota,2018,2,663431,458270,69.1,442634,66.7,15636,3.4
26809,47,Tennessee,2018,2,5315710,3222076,60.6,3113568,58.6,108508,3.4
26810,48,Texas,2018,2,21482555,13657129,63.6,13113005,61.0,544124,4.0
26811,49,Utah,2018,2,2280339,1579065,69.2,1530424,67.1,48641,3.1
26812,50,Vermont,2018,2,516278,345939,67.0,336220,65.1,9719,2.8
26813,51,Virginia,2018,2,6640456,4320994,65.1,4171274,62.8,149720,3.5
26814,53,Washington,2018,2,5896689,3759850,63.8,3581970,60.7,177880,4.7
26815,54,West Virginia,2018,2,1456688,784769,53.9,742554,51.0,42215,5.4
26816,55,Wisconsin,2018,2,4608690,3160968,68.6,3068175,66.6,92793,2.9
26817,56,Wyoming,2018,2,445707,291488,65.4,279937,62.8,11551,4.0

In [ ]:
type ('State and area')

In [133]:
df.columns

Index([                    u'FIPS Code',                u'State and area',
                                u'Year',                         u'Month',
       u'Civilian non-Inst. population',          u'Civilian labor force',
                      u'CL-Pct of Pop.',                    u'Employment',
                       u'E-Pct of Pop.',                    u'Unemployed',
                              u'U-Rate',                     u'FIPS code'],
      dtype='object')

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26818 entries, 0 to 26817
Data columns (total 12 columns):
FIPS Code                        26818 non-null int64
State and area                   26818 non-null object
Year                             26818 non-null int64
Month                            26818 non-null int64
Civilian non-Inst. population    26818 non-null int64
Civilian labor force             26818 non-null int64
CL-Pct of Pop.                   26818 non-null float64
Employment                       26818 non-null int64
E-Pct of Pop.                    26818 non-null float64
Unemployed                       26818 non-null int64
U-Rate                           26818 non-null float64
FIPS code                        26818 non-null int64
dtypes: float64(3), int64(8), object(1)
memory usage: 2.5+ MB

In [14]:
address = "State-LFPRates.xlsx"
krate = pd.read_excel(address)
krate.columns = ['FIPS Code', 'State and area', 'Year', 'Month', 'Civilian non-Inst. population', 'CL-Pct of Pop.','Civilian labor force','CL-Pct of Pop.','Employment', 'E-Pct of Pop.' 'Unemployed', 'U-Rate']

krate.head()

krate_group = krate.groupby(krate['State and area'])
df[df['State and area'].str.match('Massachusetts')]
df[df['State and area'].str.match('New Jersey')]

,FIPS Code,State and area,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate
31,34,New Jersey,1976,1,5358000,3281099,61.2,2944762,55.0,336337,10.3
84,34,New Jersey,1976,2,5363000,3280097,61.2,2944167,54.9,335930,10.2
137,34,New Jersey,1976,3,5367000,3282199,61.2,2945972,54.9,336227,10.2
190,34,New Jersey,1976,4,5372000,3290889,61.3,2952460,55.0,338429,10.3
243,34,New Jersey,1976,5,5376000,3301261,61.4,2960089,55.1,341172,10.3
296,34,New Jersey,1976,6,5381000,3311189,61.5,2967398,55.1,343791,10.4
349,34,New Jersey,1976,7,5385000,3318401,61.6,2972413,55.2,345988,10.4
402,34,New Jersey,1976,8,5389000,3323094,61.7,2975450,55.2,347644,10.5
455,34,New Jersey,1976,9,5394000,3327480,61.7,2978004,55.2,349476,10.5
508,34,New Jersey,1976,10,5398000,3333000,61.7,2980622,55.2,352378,10.6
561,34,New Jersey,1976,11,5403000,3340512,61.8,2984304,55.2,356208,10.7
614,34,New Jersey,1976,12,5407000,3349255,61.9,2990493,55.3,358762,10.7
667,34,New Jersey,1977,1,5411000,3358839,62.1,3000405,55.5,358434,10.7
720,34,New Jersey,1977,2,5416000,3368520,62.2,3013869,55.6,354651,10.5
773,34,New Jersey,1977,3,5420000,3376107,62.3,3028935,55.9,347172,10.3
826,34,New Jersey,1977,4,5425000,3380846,62.3,3043611,56.1,337235,10.0
879,34,New Jersey,1977,5,5429000,3382905,62.3,3056295,56.3,326610,9.7
932,34,New Jersey,1977,6,5434000,3383078,62.3,3066068,56.4,317010,9.4
985,34,New Jersey,1977,7,5438000,3383198,62.2,3073829,56.5,309369,9.1
1038,34,New Jersey,1977,8,5443000,3385038,62.2,3081806,56.6,303232,9.0
1091,34,New Jersey,1977,9,5449000,3388938,62.2,3091686,56.7,297252,8.8
1144,34,New Jersey,1977,10,5454000,3393355,62.2,3103291,56.9,290064,8.5
1197,34,New Jersey,1977,11,5459000,3396976,62.2,3115597,57.1,281379,8.3
1250,34,New Jersey,1977,12,5464000,3399539,62.2,3127266,57.2,272273,8.0
1303,34,New Jersey,1978,1,5470000,3402187,62.2,3138336,57.4,263851,7.8
1356,34,New Jersey,1978,2,5475000,3406882,62.2,3149507,57.5,257375,7.6
1409,34,New Jersey,1978,3,5480000,3415348,62.3,3161677,57.7,253671,7.4
1462,34,New Jersey,1978,4,5485000,3427629,62.5,3175428,57.9,252201,7.4
1515,34,New Jersey,1978,5,5491000,3443104,62.7,3191130,58.1,251974,7.3
1568,34,New Jersey,1978,6,5496000,3460159,63.0,3208664,58.4,251495,7.3
...,...,...,...,...,...,...,...,...,...,...,...
25259,34,New Jersey,2015,9,7097965,4526812,63.8,4284395,60.4,242417,5.4
25312,34,New Jersey,2015,10,7101393,4526413,63.7,4290296,60.4,236117,5.2
25365,34,New Jersey,2015,11,7104042,4528761,63.7,4296943,60.5,231818,5.1
25418,34,New Jersey,2015,12,7106698,4532336,63.8,4302757,60.5,229579,5.1
25471,34,New Jersey,2016,1,7108635,4535191,63.8,4306309,60.6,228882,5.0
25524,34,New Jersey,2016,2,7110505,4536386,63.8,4307177,60.6,229209,5.1
25577,34,New Jersey,2016,3,7112628,4535566,63.8,4305784,60.5,229782,5.1
25630,34,New Jersey,2016,4,7115049,4533694,63.7,4303477,60.5,230217,5.1
25683,34,New Jersey,2016,5,7117550,4532105,63.7,4301765,60.4,230340,5.1
25736,34,New Jersey,2016,6,7120079,4530971,63.6,4301331,60.4,229640,5.1
25789,34,New Jersey,2016,7,7123058,4530152,63.6,4302316,60.4,227836,5.0
25842,34,New Jersey,2016,8,7126751,4529680,63.6,4304193,60.4,225487,5.0
25895,34,New Jersey,2016,9,7130558,4529695,63.5,4306315,60.4,223380,4.9
25948,34,New Jersey,2016,10,7134507,4529314,63.5,4308285,60.4,221029,4.9
26001,34,New Jersey,2016,11,7137883,4528191,63.4,4310393,60.4,217798,4.8
26054,34,New Jersey,2016,12,7140892,4526537,63.4,4312683,60.4,213854,4.7
26107,34,New Jersey,2017,1,7144128,4524882,63.3,4315001,60.4,209881,4.6
26160,34,New Jersey,2017,2,7146184,4523440,63.3,4317138,60.4,206302,4.6
26213,34,New Jersey,2017,3,7148437,4522064,63.3,4318174,60.4,203890,4.5
26266,34,New Jersey,2017,4,7150924,4521156,63.2,4318031,60.4,203125,4.5
26319,34,New Jersey,2017,5,7153747,4520848,63.2,4316982,60.3,203866,4.5
26372,34,New Jersey,2017,6,7156668,4521158,63.2,4315167,60.3,205991,4.6
26425,34,New Jersey,2017,7,7159985,4521445,63.1,4312397,60.2,209048,4.6
26478,34,New Jersey,2017,8,7163572,4520146,63.1,4308354,60.1,211792,4.7
26531,34,New Jersey,2017,9,7167163,4518109,63.0,4304556,60.1,213553,4.7
26584,34,New Jersey,2017,10,7170755,4515353,63.0,4301089,60.0,214264,4.7
26637,34,New Jersey,2017,11,7173770,4513889,62.9,4299951,59.9,213938,4.7
26690,34,New Jersey,2017,12,7176397,4513664,62.9,4300174,59.9,213490,4.7
26743,34,New Jersey,2018,1,7179101,4508665,62.8,4296896,59.9,211769,4.7
26796,34,New Jersey,2018,2,7180959,4506605,62.8,4297507,59.8,209098,4.6

In [ ]:
g = df.groupby("Month")
g

In [ ]:
for 'State and area' in g:
    print("State and area:",'State and area')
    print("\n")

In [118]:
df ['State and area'] = 'Massachusetts'
df

,FIPS Code,State and area,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate,FIPS code
0,25,Massachusetts,1976,1,2605000,1492409,57.3,1392154,53.4,100255,6.7,25
1,25,Massachusetts,1976,1,232000,159154,68.6,147809,63.7,11345,7.1,25
2,25,Massachusetts,1976,1,1621000,972413,60.0,872738,53.8,99675,10.3,25
3,25,Massachusetts,1976,1,1536000,882835,57.5,817756,53.2,65079,7.4,25
4,25,Massachusetts,1976,1,15621000,9781720,62.6,8892663,56.9,889057,9.1,25
5,25,Massachusetts,1976,1,5273000,3375681,64.0,3078200,58.4,297481,8.8,25
6,25,Massachusetts,1976,1,1832000,1232334,67.3,1164563,63.6,67771,5.5,25
7,25,Massachusetts,1976,1,2248000,1443606,64.2,1302422,57.9,141184,9.8,25
8,25,Massachusetts,1976,1,417000,262688,63.0,242382,58.1,20306,7.7,25
9,25,Massachusetts,1976,1,520000,339378,65.3,308820,59.4,30558,9.0,25
10,25,Massachusetts,1976,1,6421000,3592149,55.9,3248523,50.6,343626,9.6,25
11,25,Massachusetts,1976,1,3522000,2250451,63.9,2061744,58.5,188707,8.4,25
12,25,Massachusetts,1976,1,583000,408869,70.1,367414,63.0,41455,10.1,25
13,25,Massachusetts,1976,1,580000,366173,63.1,346216,59.7,19957,5.5,25
14,25,Massachusetts,1976,1,8127000,5133491,63.2,4788469,58.9,345022,6.7,25
15,25,Massachusetts,1976,1,3789000,2418961,63.8,2260951,59.7,158010,6.5,25
16,25,Massachusetts,1976,1,2066000,1324627,64.1,1269103,61.4,55524,4.2,25
17,25,Massachusetts,1976,1,1635000,1061055,64.9,1015585,62.1,45470,4.3,25
18,25,Massachusetts,1976,1,2459000,1489641,60.6,1406646,57.2,82995,5.6,25
19,25,Massachusetts,1976,1,2672000,1513827,56.7,1417816,53.1,96011,6.3,25
20,25,Massachusetts,1976,1,764000,475639,62.3,433990,56.8,41649,8.8,25
21,25,Massachusetts,1976,1,2954000,1905561,64.5,1781850,60.3,123711,6.5,25
22,25,Massachusetts,1976,1,4194000,2715161,64.7,2435124,58.1,280037,10.3,25
23,25,Massachusetts,1976,1,6417000,3959251,61.7,3568988,55.6,390263,9.9,25
24,25,Massachusetts,1976,1,2788000,1832797,65.7,1722777,61.8,110020,6.0,25
25,25,Massachusetts,1976,1,1640000,961115,58.6,896774,54.7,64341,6.7,25
26,25,Massachusetts,1976,1,3464000,2088814,60.3,1963951,56.7,124863,6.0,25
27,25,Massachusetts,1976,1,531000,327276,61.6,308066,58.0,19210,5.9,25
28,25,Massachusetts,1976,1,1095000,715752,65.4,692137,63.2,23615,3.3,25
29,25,Massachusetts,1976,1,451000,322417,71.5,293574,65.1,28843,8.9,25
...,...,...,...,...,...,...,...,...,...,...,...,...
26788,25,Massachusetts,2018,2,7967153,4897505,61.5,4664835,58.6,232670,4.8,25
26789,25,Massachusetts,2018,2,4393144,3085973,70.2,2986231,68.0,99742,3.2,25
26790,25,Massachusetts,2018,2,2291935,1274048,55.6,1216375,53.1,57673,4.5,25
26791,25,Massachusetts,2018,2,4796357,3040940,63.4,2929814,61.1,111126,3.7,25
26792,25,Massachusetts,2018,2,838288,526548,62.8,504872,60.2,21676,4.1,25
26793,25,Massachusetts,2018,2,1472932,1009356,68.5,980975,66.6,28381,2.8,25
26794,25,Massachusetts,2018,2,2381974,1480436,62.2,1407920,59.1,72516,4.9,25
26795,25,Massachusetts,2018,2,1105804,747182,67.6,727999,65.8,19183,2.6,25
26796,25,Massachusetts,2018,2,7180959,4506605,62.8,4297507,59.8,209098,4.6,25
26797,25,Massachusetts,2018,2,1624419,935149,57.6,881222,54.2,53927,5.8,25
26798,25,Massachusetts,2018,2,15960578,9692497,60.7,9242364,57.9,450133,4.6,25
26799,25,Massachusetts,2018,2,6944935,4228210,60.9,4048517,58.3,179693,4.2,25
26800,25,Massachusetts,2018,2,8101027,4974418,61.4,4751873,58.7,222545,4.5,25
26801,25,Massachusetts,2018,2,579228,413631,71.4,402694,69.5,10937,2.6,25
26802,25,Massachusetts,2018,2,9213291,5765751,62.6,5504161,59.7,261590,4.5,25
26803,25,Massachusetts,2018,2,3004345,1845167,61.4,1770033,58.9,75134,4.1,25
26804,25,Massachusetts,2018,2,3361594,2129855,63.4,2041949,60.7,87906,4.1,25
26805,25,Massachusetts,2018,2,10276743,6410846,62.4,6100869,59.4,309977,4.8,25
26806,25,Massachusetts,2018,2,864323,557339,64.5,532007,61.6,25332,4.5,25
26807,25,Massachusetts,2018,2,3986188,2324714,58.3,2223298,55.8,101416,4.4,25
26808,25,Massachusetts,2018,2,663431,458270,69.1,442634,66.7,15636,3.4,25
26809,25,Massachusetts,2018,2,5315710,3222076,60.6,3113568,58.6,108508,3.4,25
26810,25,Massachusetts,2018,2,21482555,13657129,63.6,13113005,61.0,544124,4.0,25
26811,25,Massachusetts,2018,2,2280339,1579065,69.2,1530424,67.1,48641,3.1,25
26812,25,Massachusetts,2018,2,516278,345939,67.0,336220,65.1,9719,2.8,25
26813,25,Massachusetts,2018,2,6640456,4320994,65.1,4171274,62.8,149720,3.5,25
26814,25,Massachusetts,2018,2,5896689,3759850,63.8,3581970,60.7,177880,4.7,25
26815,25,Massachusetts,2018,2,1456688,784769,53.9,742554,51.0,42215,5.4,25
26816,25,Massachusetts,2018,2,4608690,3160968,68.6,3068175,66.6,92793,2.9,25
26817,25,Massachusetts,2018,2,445707,291488,65.4,279937,62.8,11551,4.0,25

In [129]:
ticks = df.loc[:, ['FIPS Code', 'State and area']]
ticks.head()

   FIPS Code State and area
0         25  Massachusetts
1         25  Massachusetts
2         25  Massachusetts
3         25  Massachusetts
4         25  Massachusetts

In [136]:
url = 'https://raw.github.com/gjreda/best-sandwiches/master/data/best-sandwiches-geocode.tsv'

# fetch the text from the URL and read it into a DataFrame
from_url = pd.read_table(url, sep='\t')
from_url.head(3)

,rank,sandwich,restaurant,description,price,address,city,phone,website,full_address,formatted_address,lat,lng
0,1,BLT,Old Oak Tap,The B is applewood smoked&mdash;nice and snapp...,$10,2109 W. Chicago Ave.,Chicago,773-772-0406,theoldoaktap.com,"2109 W. Chicago Ave., Chicago","2109 West Chicago Avenue, Chicago, IL 60622, USA",41.895734,-87.679960
1,2,Fried Bologna,Au Cheval,Thought your bologna-eating days had retired w...,$9,800 W. Randolph St.,Chicago,312-929-4580,aucheval.tumblr.com,"800 W. Randolph St., Chicago","800 West Randolph Street, Chicago, IL 60607, USA",41.884672,-87.647754
2,3,Woodland Mushroom,Xoco,Leave it to Rick Bayless and crew to come up w...,$9.50.,445 N. Clark St.,Chicago,312-334-3688,rickbayless.com,"445 N. Clark St., Chicago","445 North Clark Street, Chicago, IL 60654, USA",41.890602,-87.630925

In [139]:
print('Massachusetts' in 'State and area')

False

In [142]:
# read from Excel
states = pd.read_excel('State-LFPRates.xlsx')
states

,FIPS Code,State and area,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate
0,1,Alabama,1976,1,2605000,1492409,57.3,1392154,53.4,100255,6.7
1,2,Alaska,1976,1,232000,159154,68.6,147809,63.7,11345,7.1
2,4,Arizona,1976,1,1621000,972413,60.0,872738,53.8,99675,10.3
3,5,Arkansas,1976,1,1536000,882835,57.5,817756,53.2,65079,7.4
4,6,California,1976,1,15621000,9781720,62.6,8892663,56.9,889057,9.1
5,37,Los Angeles County,1976,1,5273000,3375681,64.0,3078200,58.4,297481,8.8
6,8,Colorado,1976,1,1832000,1232334,67.3,1164563,63.6,67771,5.5
7,9,Connecticut,1976,1,2248000,1443606,64.2,1302422,57.9,141184,9.8
8,10,Delaware,1976,1,417000,262688,63.0,242382,58.1,20306,7.7
9,11,District of Columbia,1976,1,520000,339378,65.3,308820,59.4,30558,9.0
10,12,Florida,1976,1,6421000,3592149,55.9,3248523,50.6,343626,9.6
11,13,Georgia,1976,1,3522000,2250451,63.9,2061744,58.5,188707,8.4
12,15,Hawaii,1976,1,583000,408869,70.1,367414,63.0,41455,10.1
13,16,Idaho,1976,1,580000,366173,63.1,346216,59.7,19957,5.5
14,17,Illinois,1976,1,8127000,5133491,63.2,4788469,58.9,345022,6.7
15,18,Indiana,1976,1,3789000,2418961,63.8,2260951,59.7,158010,6.5
16,19,Iowa,1976,1,2066000,1324627,64.1,1269103,61.4,55524,4.2
17,20,Kansas,1976,1,1635000,1061055,64.9,1015585,62.1,45470,4.3
18,21,Kentucky,1976,1,2459000,1489641,60.6,1406646,57.2,82995,5.6
19,22,Louisiana,1976,1,2672000,1513827,56.7,1417816,53.1,96011,6.3
20,23,Maine,1976,1,764000,475639,62.3,433990,56.8,41649,8.8
21,24,Maryland,1976,1,2954000,1905561,64.5,1781850,60.3,123711,6.5
22,25,Massachusetts,1976,1,4194000,2715161,64.7,2435124,58.1,280037,10.3
23,26,Michigan,1976,1,6417000,3959251,61.7,3568988,55.6,390263,9.9
24,27,Minnesota,1976,1,2788000,1832797,65.7,1722777,61.8,110020,6.0
25,28,Mississippi,1976,1,1640000,961115,58.6,896774,54.7,64341,6.7
26,29,Missouri,1976,1,3464000,2088814,60.3,1963951,56.7,124863,6.0
27,30,Montana,1976,1,531000,327276,61.6,308066,58.0,19210,5.9
28,31,Nebraska,1976,1,1095000,715752,65.4,692137,63.2,23615,3.3
29,32,Nevada,1976,1,451000,322417,71.5,293574,65.1,28843,8.9
...,...,...,...,...,...,...,...,...,...,...,...
26788,26,Michigan,2018,2,7967153,4897505,61.5,4664835,58.6,232670,4.8
26789,27,Minnesota,2018,2,4393144,3085973,70.2,2986231,68.0,99742,3.2
26790,28,Mississippi,2018,2,2291935,1274048,55.6,1216375,53.1,57673,4.5
26791,29,Missouri,2018,2,4796357,3040940,63.4,2929814,61.1,111126,3.7
26792,30,Montana,2018,2,838288,526548,62.8,504872,60.2,21676,4.1
26793,31,Nebraska,2018,2,1472932,1009356,68.5,980975,66.6,28381,2.8
26794,32,Nevada,2018,2,2381974,1480436,62.2,1407920,59.1,72516,4.9
26795,33,New Hampshire,2018,2,1105804,747182,67.6,727999,65.8,19183,2.6
26796,34,New Jersey,2018,2,7180959,4506605,62.8,4297507,59.8,209098,4.6
26797,35,New Mexico,2018,2,1624419,935149,57.6,881222,54.2,53927,5.8
26798,36,New York,2018,2,15960578,9692497,60.7,9242364,57.9,450133,4.6
26799,51000,New York city,2018,2,6944935,4228210,60.9,4048517,58.3,179693,4.2
26800,37,North Carolina,2018,2,8101027,4974418,61.4,4751873,58.7,222545,4.5
26801,38,North Dakota,2018,2,579228,413631,71.4,402694,69.5,10937,2.6
26802,39,Ohio,2018,2,9213291,5765751,62.6,5504161,59.7,261590,4.5
26803,40,Oklahoma,2018,2,3004345,1845167,61.4,1770033,58.9,75134,4.1
26804,41,Oregon,2018,2,3361594,2129855,63.4,2041949,60.7,87906,4.1
26805,42,Pennsylvania,2018,2,10276743,6410846,62.4,6100869,59.4,309977,4.8
26806,44,Rhode Island,2018,2,864323,557339,64.5,532007,61.6,25332,4.5
26807,45,South Carolina,2018,2,3986188,2324714,58.3,2223298,55.8,101416,4.4
26808,46,South Dakota,2018,2,663431,458270,69.1,442634,66.7,15636,3.4
26809,47,Tennessee,2018,2,5315710,3222076,60.6,3113568,58.6,108508,3.4
26810,48,Texas,2018,2,21482555,13657129,63.6,13113005,61.0,544124,4.0
26811,49,Utah,2018,2,2280339,1579065,69.2,1530424,67.1,48641,3.1
26812,50,Vermont,2018,2,516278,345939,67.0,336220,65.1,9719,2.8
26813,51,Virginia,2018,2,6640456,4320994,65.1,4171274,62.8,149720,3.5
26814,53,Washington,2018,2,5896689,3759850,63.8,3581970,60.7,177880,4.7
26815,54,West Virginia,2018,2,1456688,784769,53.9,742554,51.0,42215,5.4
26816,55,Wisconsin,2018,2,4608690,3160968,68.6,3068175,66.6,92793,2.9
26817,56,Wyoming,2018,2,445707,291488,65.4,279937,62.8,11551,4.0

In [144]:
states.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26818 entries, 0 to 26817
Data columns (total 11 columns):
FIPS Code                        26818 non-null int64
State and area                   26818 non-null object
Year                             26818 non-null int64
Month                            26818 non-null int64
Civilian non-Inst. population    26818 non-null int64
Civilian labor force             26818 non-null int64
CL-Pct of Pop.                   26818 non-null float64
Employment                       26818 non-null int64
E-Pct of Pop.                    26818 non-null float64
Unemployed                       26818 non-null int64
U-Rate                           26818 non-null float64
dtypes: float64(3), int64(7), object(1)
memory usage: 2.3+ MB

In [146]:
states.dtypes

FIPS Code                          int64
State and area                    object
Year                               int64
Month                              int64
Civilian non-Inst. population      int64
Civilian labor force               int64
CL-Pct of Pop.                   float64
Employment                         int64
E-Pct of Pop.                    float64
Unemployed                         int64
U-Rate                           float64
dtype: object

In [148]:
states.describe()

,FIPS Code,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate
count,26818.000000,26818.000000,26818.000000,2.681800e+04,2.681800e+04,26818.000000,2.681800e+04,26818.000000,2.681800e+04,26818.000000
mean,990.830189,1996.584980,6.480237,4.123725e+06,2.676443e+06,65.813741,2.506278e+06,61.855150,1.701647e+05,6.072925
std,6935.170515,12.172155,3.459685,4.453745e+06,2.867184e+06,4.239998,2.673396e+06,4.732795,2.107074e+05,2.109033
min,1.000000,1976.000000,1.000000,2.320000e+05,1.589610e+05,50.300000,1.476660e+05,42.200000,5.488000e+03,2.100000
25%,17.000000,1986.000000,3.000000,1.074980e+06,7.058398e+05,63.100000,6.682028e+05,58.800000,3.762000e+04,4.600000
50%,30.000000,1997.000000,6.000000,2.868242e+06,1.842620e+06,66.200000,1.721234e+06,62.100000,1.065785e+05,5.700000
75%,42.000000,2007.000000,9.000000,5.188886e+06,3.329468e+06,68.700000,3.136299e+06,65.200000,2.133958e+05,7.300000
max,51000.000000,2018.000000,12.000000,3.114640e+07,1.939295e+07,75.600000,1.854952e+07,73.100000,2.253816e+06,18.800000

In [150]:
states.head(5)

,FIPS Code,State and area,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate
0,1,Alabama,1976,1,2605000,1492409,57.3,1392154,53.4,100255,6.7
1,2,Alaska,1976,1,232000,159154,68.6,147809,63.7,11345,7.1
2,4,Arizona,1976,1,1621000,972413,60.0,872738,53.8,99675,10.3
3,5,Arkansas,1976,1,1536000,882835,57.5,817756,53.2,65079,7.4
4,6,California,1976,1,15621000,9781720,62.6,8892663,56.9,889057,9.1

In [153]:
states[27:42]

,FIPS Code,State and area,Year,Month,Civilian non-Inst. population,Civilian labor force,CL-Pct of Pop.,Employment,E-Pct of Pop.,Unemployed,U-Rate
27,30,Montana,1976,1,531000,327276,61.6,308066,58.0,19210,5.9
28,31,Nebraska,1976,1,1095000,715752,65.4,692137,63.2,23615,3.3
29,32,Nevada,1976,1,451000,322417,71.5,293574,65.1,28843,8.9
30,33,New Hampshire,1976,1,593000,391585,66.0,364963,61.5,26622,6.8
31,34,New Jersey,1976,1,5358000,3281099,61.2,2944762,55.0,336337,10.3
32,35,New Mexico,1976,1,792000,475004,60.0,432875,54.7,42129,8.9
33,36,New York,1976,1,13196000,7687165,58.3,6896554,52.3,790611,10.3
34,51000,New York city,1976,1,5694000,3114007,54.7,2768623,48.6,345384,11.1
35,37,North Carolina,1976,1,3898000,2596329,66.6,2428430,62.3,167899,6.5
36,38,North Dakota,1976,1,442000,275609,62.4,266394,60.3,9215,3.3
37,39,Ohio,1976,1,7701000,4756109,61.8,4371860,56.8,384249,8.1
38,40,Oklahoma,1976,1,1999000,1180825,59.1,1110620,55.6,70205,5.9
39,41,Oregon,1976,1,1716000,1074151,62.6,969974,56.5,104177,9.7
40,42,Pennsylvania,1976,1,8774000,5105548,58.2,4693332,53.5,412216,8.1
41,44,Rhode Island,1976,1,691000,434960,62.9,399599,57.8,35361,8.1

In [15]:
states['State and area'].head(51)

NameError: name 'states' is not defined

In [164]:
from IPython.core.display import HTML
HTML("<iframe src=http://www.bls.gov width=800 height=350></iframe>")

In [16]:
type(states)

NameError: name 'states' is not defined

In [17]:
states.loc[12321]

NameError: name 'states' is not defined

In [18]:
states.info()

NameError: name 'states' is not defined

In [186]:
states.dtypes

FIPS Code                          int64
State and area                    object
Year                               int64
Month                              int64
Civilian non-Inst. population      int64
Civilian labor force               int64
CL-Pct of Pop.                   float64
Employment                         int64
E-Pct of Pop.                    float64
Unemployed                         int64
U-Rate                           float64
dtype: object

In [188]:
#import webbrowser
#webbrowser.open ('http://www.bls.gov/')

True

In [191]:
import types
def imports():
    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            yield val.__name__
list(imports())

['IPython.core.shadowns',
 'requests',
 'sys',
 '__builtin__',
 '__builtin__',
 'pandas',
 'webbrowser',
 'types']